Initial stab at abstracted dependency handling/cleanup

diff --git a/targets/packages/build b/targets/packages/build
--- a/targets/packages/build
+++ b/targets/packages/build
@@ -67,24 +67,229 @@ EOF
 
 buildpackage() {
     # Build the package.
-    message info "Building the package..."
-    # TODO: We appear to need this 'special' path for fakechroot chroots, as
-    #       fakechroot is not 100% reliable...
-    # TODO: Find a better fakechroot alternative?
-    PATH="${basedir}/opt/${config[triplet]}/bin:${PATH}" \
-        fakechroot chroot "${basedir}" /build.sh || \
-        error "$?" "Running makepkg failed!"
-}
-
-hostpacman() {
-    # Run pacman on the host.
     local basedir="$1"
-    shift
+    local prefix="$2"
 
-    fakechroot fakeroot pacman --cachedir /var/cache/pacman/pkg \
-        --noconfirm --root "${basedir}" "$@" || \
-        error 1 "Failed to run pacman on the chroot!"
+    message info "Building the package..."
+
+    if [ "${prefix}" == "native" ]; then
+        error 1 "QEMU support is not yet implemented!"
+        # TODO: How much RAM is a good amount?
+        # TODO: Can I use /build.sh as an init?
+        "${configdir}/qemu" \
+            -kernel $kernel \
+            -append "console=ttyS0 init=/build.sh root=/dev/sda1 panic=10" \
+            -hda "fat:${basedir}" \
+            -m 128 \
+            -no-reboot -nographic
+    else
+        # TODO: We appear to need this 'special' path for fakechroot chroots,
+        #       as fakechroot is not 100% reliable...
+        # TODO: Find a better fakechroot alternative?
+        PATH="${basedir}/opt/${config[triplet]}/bin:${PATH}" \
+            fakechroot chroot "${basedir}" /build.sh || \
+            error "$?" "Running makepkg failed!"
+    fi
 }
+
+checkprov() {
+    # Fail if there are too many providers.
+    dep="$1"
+    shift
+    if [ "$(printf "%s\n" "$@" | wc -l)" -gt 1 ]; then
+        error 1 "Too many providers found for '${dep}': $@"
+    elif [ -z "$1" ]; then
+        error 1 "No providers found for '${dep}'!"
+    fi
+}
+
+installdeps() {
+    local configdir="$1"
+    local target="$2"
+    local basedir="$3"
+
+    # Keep track of the dependencies corresponding to the various dirs.
+    local tooldepends crossdepends nativedepends
+    declare -a tooldepends
+    declare -a crossdepends
+    declare -a nativedepends
+
+    # Declare the vars for the graph traversal.
+    local visited stack
+    declare -A visited
+    declare -a stack
+
+    # Initialise the stack and visited hash.
+    # We cannot just put the target on the stack, as it has a different
+    # dependency generation script, and should not end up in *depends.
+    local deps
+    deps="$("$(dirname "$0")/../../scripts/lsdeps.sh" \
+        <(genmakepkgconf "${configdir}" "${target}") \
+        "${configdir}/src/${target}/PKGBUILD")" || \
+        error 1 "Failed to extract the deps from the PKGBUILD!"
+    local dep prov
+    while IFS=" " read dep prov; do
+        checkprov "${dep}" "${prov}"
+        visited["${prov}"]="${dep}"
+        stack+=("${prov}")
+    done < <(printf "%s\n" "${deps}" | \
+        findpkgdeps "${configdir}" "${current%%/*}") || \
+        error 3 "Failed to generate the package providers!"
+    
+
+    # Traverse the graph.
+    while [ "${#stack}" -gt 0 ]; do
+        # Visit each node.
+
+        # Pop the item off the top of the stack.
+        local current="${stack[-1]}"
+        stack=(${stack[@]:0:$(expr "${#stack[@]}" - 1)})
+
+        # Process the dependencies.
+        local dep prov
+        while IFS=" " read dep prov; do
+
+            message debug "${current} requires ${prov}"
+            checkprov "${dep}" "${prov}"
+
+            # If the provider is unvisited, add it to the stack and mark it
+            # as visited.
+            if [ -z "${visited["${prov}"]+is_set}" ]; then
+                visited["${prov}"]="${dep}"
+                stack+=("${prov}")
+            fi
+        done < <(sed "${configdir}/src/${current}/.SRCINFO" -n \
+            -e '/^[ \t]*depends = /p' | \
+            findpkgdeps "${configdir}" "${current%%/*}") || \
+            error 3 "Failed to generate the package providers!"
+
+        # Add the item to the appropriate list.
+        case "${current%%/*}" in
+            toolchain) tooldepends+=("${current}");;
+            packages) crossdepends+=("${current}");;
+            native) nativedepends+=("${current}");;
+            *) error 2 "Unknown provider prefix '${current%%/*}'!"
+        esac
+
+    done
+
+    # Install the dependencies.
+    installtooldeps "${configdir}" "${target%%/*}" "${basedir}" \
+        "${tooldepends[@]}"
+    installcrossdeps "${configdir}" "${target%%/*}" "${basedir}" \
+        "${crossdepends[@]}"
+    installnativedeps "${configdir}" "${target%%/*}" "${basedir}" \
+        "${nativedepends[@]}"
+}
+
+callpacman() {
+    # Call pacman on the given sysroot.
+    out="$@"
+    message debug "Running pacman with args '--noconfirm --root $out'"
+    fakechroot fakeroot pacman --noconfirm --root "$@" || \
+        error 1 "Failed to run pacman on the root!"
+}
+
+mappkgs() {
+    # Map the given dirs to actual packages.
+    # TODO: Currently, we do not preserve the actual package names, so this is
+    #       overly enthusiastic in the case of split packages.
+    local configdir="$1"
+    shift
+    local targ pkg
+    for targ in "$@"; do
+        pkgdirpackages "${configdir}" "${targ}" | \
+            while IFS= read pkg; do
+                printf "%s/pkgs/%s\n" "${configdir}" "${pkg}"
+            done || \
+                error 2 "Failed to map '${targ}' to corresponding packages!"
+    done
+}
+
+installtooldeps() {
+    # Install the given list of host deps.
+    # Fall back to the host packages if no matching packages are found.
+    local configdir="$1"
+    local prefix="$2"
+    local basedir="$3"
+    shift 3
+    if [ "$#" -eq 0 ]; then return; fi
+
+    if [ "${prefix}" == "native" ]; then
+        error 1 "Cannot install host deps to a native root!"
+    fi
+
+    message info "Installing toolchain packages to ${basedir}:"
+    for i in "$@"; do message info "    $i"; done
+
+    # Initialise the pacman sync databases.
+    mkdir -p "${basedir}/var/lib/pacman" && \
+        fakeroot cp -p -r /var/lib/pacman/sync "${basedir}/var/lib/pacman" || \
+        error 1 "Failed to copy the host sync databases!"
+    # Install base-devel.
+    # TODO: This takes a while, and is dependent on the local pacman.conf.
+    #       What would be a better method?
+    #       Can I cache this (in a tarball, perhaps?) and extract it before
+    #       building anything? Would that be faster?
+    callpacman "${basedir}" --cachedir /var/cache/pacman/pkg -S base-devel 
+    
+    # Install the given packages.
+    callpacman "${basedir}" --cachedir /var/cache/pacman/pkg -U \
+        $(mappkgs "${configdir}" "$@")
+}
+
+installcrossdeps() {
+    # Install the given list of cross compiled deps.
+    local configdir="$1"
+    local prefix="$2"
+    local basedir="$3"
+    shift 3
+    if [ "$#" -eq 0 ]; then return; fi
+
+    if [ "${prefix}" == "native" ]; then
+        local root="${basedir}"
+    else
+        local root="${basedir}/sysroot/"
+    fi
+
+    message info "Installing cross compiled packages to ${root}:"
+    for i in "$@"; do message info "    $i"; done
+
+    # Set up the root.
+    if [ ! -d "${root}/var/lib/pacman" ]; then
+        mkdir -p "${root}/var/lib/pacman"
+    fi
+
+    # Install the given packages.
+    callpacman "${root}" --arch "${config[arch]}" \
+        -U $(mappkgs "${configdir}" "$@")
+}
+
+installnativedeps() {
+    # Install the given list of native deps.
+    local configdir="$1"
+    local prefix="$2"
+    local basedir="$3"
+    shift 3
+    if [ "$#" -eq 0 ]; then return; fi
+
+    if [ "${prefix}" != "native" ]; then
+        error 1 "Cannot install native deps to a non-native root!"
+    fi
+
+    message info "Installing native packages to ${basedir}:"
+    for i in "$@"; do message info "    $i"; done
+
+    # Set up the root.
+    if [ ! -d "${basedir}/var/lib/pacman" ]; then
+        mkdir -p "${basedir}/var/lib/pacman"
+    fi
+
+    # Install the given packages.
+    callpacman "${basedir}" --arch "${config[arch]}" \
+        -U $(mappkgs "${configdir}" "$@")
+}
+
 
 # Prepare the sysroot.
 # Create the base dir.
@@ -94,147 +299,16 @@ fi
 mkdir -p "${basedir}" || error 1 "Failed to create build dir '${basedir}'!"
 # Populate the sysroot.
 message info "Populating the sysroot..."
-if [ "${prefix}" == "toolchain" ] || [ "${prefix}" == "packages" ]; then
-    # The sysroot is a "host" chroot; use the native packages.
-    # TODO: This takes a while, and is dependent on the local pacman.conf.
-    #       What would be a better method?
-    #       Can I cache this (in a tarball, perhaps?) and extract it before
-    #       building anything?
-    mkdir -p "${basedir}/var/lib/pacman" && \
-        fakeroot cp -p -r /var/lib/pacman/sync "${basedir}/var/lib/pacman" && \
-        hostpacman "${basedir}" -S base-devel
-else
-    # The chroot is a "target" chroot; use the cross-compiled packages.
-    : # TODO: Implement.
-fi
+installdeps "${configdir}" "${target}" "${basedir}"
 # Extract the source tarball.
 message info "Unpacking the source tarball..."
 extractsrctar "${configdir}" "${target}" "${basedir}"
-
-# Dependency resolution.
-# TODO: Dependencies *should* be evaluated using a graph.
-message info "Resolving remaining dependencies..."
-deps="$("$(dirname "$0")/../../scripts/lsdeps.sh" \
-    <(genmakepkgconf "${configdir}" "${target}") "${path}/PKGBUILD")" || \
-    error 1 "Failed to extract the deps from the PKGBUILD!"
-hostinstall() {
-    # Install the given package to the host chroot.
-    local pkg="$1"
-
-    if pacman -Q --root "${basedir}" "${pkg}" > /dev/null 2>&1; then
-        # Package is already installed; bail.
-        return
-    fi
-
-    message info "Installing host package ${pkg}..."
-
-    local providers="$(findpkgdir "${configdir}" "${pkg}" "toolchain")" || \
-        error 1 "Failed to generate providers for '${pkg}'!"
-    local provcount="$(printf "%s\n" "${providers}" | wc -l)"
-    if [ "${provcount}" -gt 1 ]; then
-        error 2 "Ambiguous package name: '${pkg}' (got '${providers}')"
-    elif [ "${provcount}" -eq 1 ] && [ -n "${providers}" ]; then
-        # Install the given package locally.
-        # TODO: This method is convoluted and installs too many packages...
-        # TODO: Reduce duplication here.
-        local pkgfiles
-        pkgfiles="$(pkgdirpackages "${configdir}" "${providers}")" || \
-            error 3 \
-            "Failed to find the packages for package dir '${providers}'!"
-        while IFS= read line; do
-            local pkgfile="${configdir}/pkgs/${line}"
-            # Install the dependencies of the package.
-            pkgdeps="$(bsdtar -O -xf "${pkgfile}" .PKGINFO | \
-                sed -n -e '/^depend = /p' | cut -d '=' -f2- | 
-                sed -e 's:[ \t]::g')" || \
-                error 4 \
-                    "Failed to generate a list of dependencies for '${pkgfile}'!"
-            printf "Deps: '${pkgdeps}' (pkgfile: ${pkgfile})\n"
-            while IFS= read dep; do
-                [ -n "${dep}" ] && hostinstall "${dep}"
-            done < <(printf "%s\n" "${pkgdeps}")
-
-            # Install the given package.
-            printf "Installing host package file '${pkgfile}'\n"
-            hostpacman "${basedir}" -U "${pkgfile}" || \
-                error 1 "Failed to install packages to sysroot: ${pkgfile}!"
-        done < <(printf "%s\n" "${pkgfiles}")
-    else
-        # Install the given package which is not provided locally.
-        hostpacman "${basedir}" --needed -S "${pkg}"
-    fi
-}
-crossinstall() {
-    # Install the given package to the sysroot.
-    local pkg="$1"
-
-    # Set up the sysroot.
-    local sysroot="${basedir}/sysroot"
-    if [ ! -d "${sysroot}/var/lib/pacman" ]; then
-        mkdir -p "${sysroot}/var/lib/pacman"
-    fi
-
-    # Bail if the package is already installed.
-    if pacman -Q --root "${sysroot}" "${pkg}" > /dev/null 2>&1; then
-        return
-    fi
-
-    message info "Installing cross package ${dep}..."
-
-    # Find the corresponding package file.
-    local providers="$(findpkgdir "${configdir}" "${pkg}" "packages")" || \
-        error 1 "Failed to generate providers for '${pkg}'!"
-    local provcount="$(printf "%s\n" "${providers}" | wc -l)"
-    if [ "${provcount}" -ne 1 ]; then
-        error 2 "Ambiguous package name: '${pkg}' (got '${providers}')"
-    fi
-    local line pkgfiles pkgdeps dep
-    # TODO: This installs too many packages.
-    pkgfiles="$(pkgdirpackages "${configdir}" "${providers}")" || \
-        error 3 "Failed to find the packages for package dir '${providers}'!"
-
-    while IFS= read line; do
-        local pkgfile="${configdir}/pkgs/${line}"
-        # Install the dependencies of the package.
-        pkgdeps="$(bsdtar -O -xf "${pkgfile}" .PKGINFO | \
-            sed -n -e '/depend = /p' | cut -d '=' -f2- | \
-            sed -e 's:[ \t]::g')" || \
-            error 4 \
-                "Failed to generate a list of dependencies for '${pkgfile}'!"
-        while IFS= read dep; do
-            [ -n "${dep}" ] && crossinstall "${dep}"
-        done < <(printf "%s\n" "${pkgdeps}")
-
-        # Install the given package.
-        fakechroot fakeroot pacman -U --noconfirm --arch "${config[arch]}" \
-            --root "${sysroot}" "${pkgfile}" || \
-            error 1 "Failed to install packages to sysroot: ${pkgfile}!"
-    done < <(printf "%s\n" "${pkgfiles}")
-}
-# Generate the deps and evaluate them.
-while IFS="= $(printf '\t\n')" read deptype dep; do
-    if [ -z "${dep}" ]; then
-        continue
-    fi
-    if [ "${deptype}" == "hostdepends" ]; then
-        # Install a package to the host chroot.
-        hostinstall "${dep}"
-    elif [ "${prefix}" == "toolchain" ] && \
-        [ "${deptype}" != "targetdepends" ]; then
-        # Install a package to the host chroot.
-        hostinstall "${dep}"
-    else
-        # Install a package to the sysroot.
-        crossinstall "${dep}"
-    fi
-done < <(printf "%s\n" "${deps}")
-
 # Generate the config files.
 message info "Generating the config files..."
 genconfigfiles "${configdir}" "${target}" "${basedir}"
 
 # Build the package.
-buildpackage
+buildpackage "${basedir}" "${prefix}"
 
 # Copy the built packages into the pkg dir.
 # TODO: Locally built (toolchain) packages are architecture specific, and
