Improved findpkgdeps

diff --git a/targets/packages/deps b/targets/packages/deps
--- a/targets/packages/deps
+++ b/targets/packages/deps
@@ -22,8 +22,10 @@ deps="$("$(dirname "$0")/../../scripts/lsdeps.sh" \
     <(genmakepkgconf "${configdir}" "${target}") "${path}")" || \
     error 1 "Failed to extract the deps from the PKGBUILD!"
 # Turn the deps into actual paths.
-printf "%s\n" "${deps}" | findpkgdeps "${configdir}" "${prefix}" || \
-    exit "$?"
+pkgpaths="$(printf "%s\n" "${deps}" | \
+    findpkgdeps "${configdir}" "${prefix}")" || \
+    error "$?" "Failed to find the package dirs!"
+printf "%s\n" "${pkgpaths}" | cut -d' ' -f2-
 # Special case 'native' packages so that they depend on base and base-devel.
 if [ "${prefix}" == "native" ]; then
     printf "targets/base\ntargets/build\n"
